In [371]:
import pandas as pd

In [372]:
import numpy as np

In [373]:
import matplotlib.pyplot as plt

In [374]:
import seaborn as sns

In [375]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [376]:
df=pd.read_csv(r'C:\Users\ZAKKI BOSS TRADERS\Desktop\ML Projects\spam_emails_raw.csv')
df

,email_id,sender,subject,body,date_received,has_attachment,num_links,label
0,E1000,ayesha3589@outlook.com,Aap ka inam nikal aya hai!! abhi claim karain,"Dear customer, you have been selected to recei...",03-28-2024 02:51,no,0,spam
1,E1001,usman7179@promo-deals.biz,"Dear beneficiary, inheritance of $4.5M",Get approved for a loan today! Bad credit...,2023-12-19 22:57,yes,1,Spam
2,E1002,sara@gmail.com,Password changed successfully,"Hi team, please find this week's report attach...",11-13-2023 12:26,FALSE,NaN,ham
3,E1003,nida@hotmail.com,FREE shipping today only,"Hi Nida, thanks for subscribing! FREE shipping...",2023/01/05,no,zero,ham
4,E1004,daniel@amazon.com,Invoice for your order #96896,"This week's newsletter: top AI papers, a tutor...",30/01/2023,No,0,0
...,...,...,...,...,...,...,...,...
493,E1493,ahmed@amazon.com,Your flight itinerary,"Hi, we are having a family dinner this Sunday ...",21/01/2023,No,0,Ham
494,E1494,ayesha8622@linkedin.com,Quick question about the code,Your password was changed successfully. If thi...,20/02/2024,No,2,ham
495,E1495,ayesha26@company.com,Course registration confirmation,"Hi Daniel, just confirming our meeting to...",2023/06/25,No,0,ham
496,E1496,ayesha1144@university.edu.pk,Assignment 84598 submission deadline,"Dear students, the deadline for assignment 881...",20 Aug 2023,0,0,not spam
497,E1497,hina4129@win-prize.info,Your flight itinerary,"Hi Omar, just confirming our meeting tomorrow ...",05-15-2023 09:31,No,1,SPAM

In [377]:
df.head()

,email_id,sender,subject,body,date_received,has_attachment,num_links,label
0,E1000,ayesha3589@outlook.com,Aap ka inam nikal aya hai!! abhi claim karain,"Dear customer, you have been selected to recei...",03-28-2024 02:51,no,0,spam
1,E1001,usman7179@promo-deals.biz,"Dear beneficiary, inheritance of $4.5M",Get approved for a loan today! Bad credit...,2023-12-19 22:57,yes,1,Spam
2,E1002,sara@gmail.com,Password changed successfully,"Hi team, please find this week's report attach...",11-13-2023 12:26,FALSE,NaN,ham
3,E1003,nida@hotmail.com,FREE shipping today only,"Hi Nida, thanks for subscribing! FREE shipping...",2023/01/05,no,zero,ham
4,E1004,daniel@amazon.com,Invoice for your order #96896,"This week's newsletter: top AI papers, a tutor...",30/01/2023,No,0,0

In [378]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   email_id        498 non-null    str
 1   sender          498 non-null    str
 2   subject         478 non-null    str
 3   body            476 non-null    str
 4   date_received   498 non-null    str
 5   has_attachment  479 non-null    str
 6   num_links       482 non-null    str
 7   label           498 non-null    str
dtypes: str(8)
memory usage: 125.2 KB

In [379]:
df.isnull().sum()

email_id           0
sender             0
subject           20
body              22
date_received      0
has_attachment    19
num_links         16
label              0
dtype: int64

In [380]:
df.duplicated().sum()

np.int64(0)

In [381]:
df=df.drop(columns=['email_id','sender','date_received'])

In [382]:
df.head()

,subject,body,has_attachment,num_links,label
0,Aap ka inam nikal aya hai!! abhi claim karain,"Dear customer, you have been selected to recei...",no,0,spam
1,"Dear beneficiary, inheritance of $4.5M",Get approved for a loan today! Bad credit...,yes,1,Spam
2,Password changed successfully,"Hi team, please find this week's report attach...",FALSE,NaN,ham
3,FREE shipping today only,"Hi Nida, thanks for subscribing! FREE shipping...",no,zero,ham
4,Invoice for your order #96896,"This week's newsletter: top AI papers, a tutor...",No,0,0

In [383]:
df.drop_duplicates()

,subject,body,has_attachment,num_links,label
0,Aap ka inam nikal aya hai!! abhi claim karain,"Dear customer, you have been selected to recei...",no,0,spam
1,"Dear beneficiary, inheritance of $4.5M",Get approved for a loan today! Bad credit...,yes,1,Spam
2,Password changed successfully,"Hi team, please find this week's report attach...",FALSE,NaN,ham
3,FREE shipping today only,"Hi Nida, thanks for subscribing! FREE shipping...",no,zero,ham
4,Invoice for your order #96896,"This week's newsletter: top AI papers, a tutor...",No,0,0
...,...,...,...,...,...
492,Quick question about the code,NaN,FALSE,0,not spam
493,Your flight itinerary,"Hi, we are having a family dinner this Sunday ...",No,0,Ham
494,Quick question about the code,Your password was changed successfully. If thi...,No,2,ham
495,Course registration confirmation,"Hi Daniel, just confirming our meeting to...",No,0,ham
496,Assignment 84598 submission deadline,"Dear students, the deadline for assignment 881...",0,0,not spam

In [384]:
df = df.drop_duplicates()

In [385]:
df.duplicated().sum()

np.int64(0)

In [386]:
df.isnull().sum()

subject           20
body              22
has_attachment    19
num_links         16
label              0
dtype: int64

In [387]:
df["has_attachment"].value_counts(dropna=False)

has_attachment
FALSE    93
No       82
0        80
no       72
yes      40
Yes      33
TRUE     32
1        29
NaN      19
Name: count, dtype: int64

In [388]:
df["num_links"].value_counts(dropna=False)

num_links
0          210
1          106
2           84
3           27
NaN         16
unknown     13
zero         6
two          6
many         5
4            1
89           1
85           1
56           1
72           1
70           1
54           1
Name: count, dtype: int64

In [389]:
df["has_attachment"] = df["has_attachment"].astype(str).str.strip().str.lower()

In [390]:
df["has_attachment"] = df["has_attachment"].replace({
    "yes": 1,
    "true": 1,
    "1": 1,
    "no": 0,
    "false": 0,
    "0": 0
})

In [391]:
df["has_attachment"] = df["has_attachment"].fillna(0)

In [392]:
df["has_attachment"].value_counts(dropna=False)

has_attachment
0    346
1    134
Name: count, dtype: int64

In [393]:
df["has_attachment"].isnull().sum()

np.int64(0)

In [394]:
df["num_links"] = df["num_links"].replace({
    "zero": 0,
    "two": 2
})

In [395]:
df["num_links"].value_counts(dropna=False)

num_links
0          210
1          106
2           84
3           27
NaN         16
unknown     13
0            6
2            6
many         5
4            1
89           1
85           1
56           1
72           1
70           1
54           1
Name: count, dtype: int64

In [396]:
df["num_links"] = df["num_links"].replace({
    "unknown": np.nan,
    "many": np.nan
})

In [397]:
df["num_links"] = pd.to_numeric(df["num_links"], errors="coerce")

In [398]:
df["num_links"].isnull().sum()

np.int64(34)

In [399]:
df["num_links"] = df["num_links"].fillna(0)

In [400]:
df["num_links"].isnull().sum()

np.int64(0)

In [401]:
df.isnull().sum()

subject           20
body              22
has_attachment     0
num_links          0
label              0
dtype: int64

In [402]:
df["subject"] = df["subject"].fillna("No Subject")

In [403]:
df["body"] = df["body"].fillna("")

In [404]:
df.isnull().sum()

subject           0
body              0
has_attachment    0
num_links         0
label             0
dtype: int64

In [405]:
df["label"].value_counts()

label
spam        131
ham         117
Ham          42
not spam     40
0            36
Not Spam     34
SPAM         31
1            26
Spam         23
Name: count, dtype: int64

In [406]:
df["label"].unique()

<ArrowStringArray>
['spam', 'Spam', 'ham', '0', 'Ham', '1', 'SPAM', 'not spam', 'Not Spam']
Length: 9, dtype: str

In [407]:
df["label"] = df["label"].str.strip().str.lower()

In [408]:
df["label"] = df["label"].replace({
    "spam": "spam",
    "1": "spam",
    "ham": "ham",
    "not spam": "ham",
    "0": "ham"})

In [409]:
df["label"].value_counts()

label
ham     269
spam    211
Name: count, dtype: int64

In [410]:
df["label"].unique()

<ArrowStringArray>
['spam', 'ham']
Length: 2, dtype: str

In [411]:
df["label"] = df["label"].map({
    "ham": 0,
    "spam": 1})

In [412]:
df["label"].value_counts()

label
0    269
1    211
Name: count, dtype: int64

In [413]:
df["text"] = df["subject"] + " " + df["body"]

In [414]:
X = df.drop(columns=["label"])
y = df["label"]

In [415]:
X_train, X_test, y_train, y_test = train_test_split(X,y,  test_size=0.2, random_state=42,stratify=y)

In [416]:
tfidf = TfidfVectorizer(
    lowercase=True,
    stop_words="english",
    max_features=3000)

In [417]:
X_train_text = tfidf.fit_transform(X_train["text"])

In [418]:
X_test_text = tfidf.transform(X_test["text"])

In [419]:
from scipy.sparse import hstack
X_train_final = hstack([
    X_train_text,
    X_train[["has_attachment", "num_links"]].astype(float).values])
X_test_final = hstack([
    X_test_text,
    X_test[["has_attachment", "num_links"]].astype(float).values])

In [420]:
models = {"Logistic Regression": LogisticRegression(max_iter=1000),"Naive Bayes": MultinomialNB(),
          "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),   "KNN": KNeighborsClassifier(n_neighbors=5),
    "Decision Tree": DecisionTreeClassifier(random_state=42),"SGD": SGDClassifier(random_state=42),"Linear SVM": LinearSVC(),}
for name, model in models.items():
    model.fit(X_train_final, y_train)
    y_pred = model.predict(X_test_final)
    accuracy = accuracy_score(y_test, y_pred)
    print(name, ":", accuracy)

Logistic Regression : 0.9791666666666666
Naive Bayes : 0.96875
Random Forest : 0.9375
KNN : 0.9270833333333334
Decision Tree : 0.9375
SGD : 0.90625
Linear SVM : 0.9791666666666666

C:\Users\ZAKKI BOSS TRADERS\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1298: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

In [421]:
for name, model in models.items():
    model.fit(X_train_final, y_train)
    y_pred = model.predict(X_test_final)
    print("\n", name)
    print("Accuracy :", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred))
    print("Recall   :", recall_score(y_test, y_pred))
    print("F1 Score :", f1_score(y_test, y_pred))

 Logistic Regression
Accuracy : 0.9791666666666666
Precision: 1.0
Recall   : 0.9523809523809523
F1 Score : 0.975609756097561

 Naive Bayes
Accuracy : 0.96875
Precision: 1.0
Recall   : 0.9285714285714286
F1 Score : 0.9629629629629629

 Random Forest
Accuracy : 0.9375
Precision: 0.9736842105263158
Recall   : 0.8809523809523809
F1 Score : 0.925

 KNN
Accuracy : 0.9270833333333334
Precision: 1.0
Recall   : 0.8333333333333334
F1 Score : 0.9090909090909091

 Decision Tree
Accuracy : 0.9375
Precision: 0.9736842105263158
Recall   : 0.8809523809523809
F1 Score : 0.925

 SGD
Accuracy : 0.90625
Precision: 0.851063829787234
Recall   : 0.9523809523809523
F1 Score : 0.898876404494382

 Linear SVM
Accuracy : 0.9791666666666666
Precision: 1.0
Recall   : 0.9523809523809523
F1 Score : 0.975609756097561

C:\Users\ZAKKI BOSS TRADERS\anaconda3\Lib\site-packages\sklearn\svm\_base.py:1298: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(